# Generated by Django 3.0.3 on 2020-02-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djuser',
            options={'verbose_name': '사용자관리', 'verbose_name_plural': '사용자관리'},
        ),
        migrations.AlterField(
            model_name='djuser',
            name='registerd_dttm',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일시'),
        ),
    ]
